import { HttpStatus } from '@nestjs/common';
import type { DomainErrorKind } from './domain.error.js';

/** Mappage centralise erreur-metier -> code HTTP, utilise par `AllExceptionsFilter`. */
export const ERROR_KIND_HTTP_STATUS: Record<DomainErrorKind, HttpStatus> = {
  VALIDATION: HttpStatus.BAD_REQUEST,
  NOT_FOUND: HttpStatus.NOT_FOUND,
  CONFLICT: HttpStatus.CONFLICT,
  FORBIDDEN: HttpStatus.FORBIDDEN,
  UNAUTHORIZED: HttpStatus.UNAUTHORIZED,
  QUOTA_EXCEEDED: HttpStatus.CONFLICT,
  INVALID_TRANSITION: HttpStatus.CONFLICT,
};

/** Catalogue des codes d'erreur metier stables (utilises par le frontend pour i18n). */
export const ErrorCodes = {
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  REQUEST_INVALID_TRANSITION: 'REQUEST_INVALID_TRANSITION',
  REQUEST_OUTSIDE_PERIOD: 'REQUEST_OUTSIDE_PERIOD',
  REQUEST_DUPLICATE_SUSPECTED: 'REQUEST_DUPLICATE_SUSPECTED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  DOCUMENT_INVALID_FORMAT: 'DOCUMENT_INVALID_FORMAT',
  DOCUMENT_TOO_LARGE: 'DOCUMENT_TOO_LARGE',
  ACCREDITATION_NOT_FOUND: 'ACCREDITATION_NOT_FOUND',
  ACCREDITATION_ALREADY_REVOKED: 'ACCREDITATION_ALREADY_REVOKED',
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
  MATCH_REQUESTS_CLOSED: 'MATCH_REQUESTS_CLOSED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_ALREADY_USED: 'USER_EMAIL_ALREADY_USED',
  USER_CANNOT_MODIFY_SELF: 'USER_CANNOT_MODIFY_SELF',
  USER_HAS_HISTORY: 'USER_HAS_HISTORY',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  FORBIDDEN_SCOPE: 'FORBIDDEN_SCOPE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
